### PR TITLE
Feat/transfer history for given token

### PR DESCRIPTION
**Pull request by luanvuonggia**
**This MR did:**

- New feature  "Check balance of user"
- New feature  "User's token transfer history for given token"
- New feature "Transfer history for given token"

**How to test:**
Run `yarn start` and go to http://localhost:3002/

Input an can account to check balance of user (I already auto fill your can account when you logged in)
Screen Shot 2020-11-27 at 11 27 28 AM

View transfer history of an token
- Go to http://localhost:3002/tranfer-history
- Enter `Code` and `Symbol` field
- Click `GET HISTORY` button for example as this picture below

Screen Shot 2020-11-30 at 2 59 47 PM

View transfer history of an user with given token, just add their can account in `CAN Account` field and token code, token symbol.

Screen Shot 2020-11-30 at 3 03 02 PM

I will write readme later when this MR be merged

@duyphanz help me check this again.

### CODE REVIEW

**Comment by duyphanz** [comment]
@manh-vv please review this MR too.

**Comment by manh-vv** [comment]
@JackVuong 

* The demonstration for the transaction history should be moved to another route so that it does not confuse the existing demonstration of signing transaction.
* Please use a common color pack to maintain the purpose of the demonstration.

It is a feature for demonstration so please add docs and it is better that you focus on making it easier for the reader to grab the idea.

**Comment by luanvuonggia** [comment]
@manh-vv  help me check again and let me know if you wanna change something.

**Comment by manh-vv** [comment]
@luanvuonggia I merged the PR. Please check it and update docs as needed.

**Pull request merged**
